# Generated by Django 5.0 on 2024-01-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
