# Generated by Django 5.0 on 2024-01-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroompost',
            name='isSeen',
            field=models.BooleanField(default=False),
        ),
    ]
