# Generated by Django 5.0 on 2024-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classroompost_isseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroompost',
            name='isSeen',
            field=models.JSONField(default=[]),
        ),
    ]
