# Generated by Django 5.0 on 2023-12-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231215_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancequestion',
            name='subject',
            field=models.TextField(),
        ),
    ]
