# Generated by Django 5.0 on 2023-12-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('member', models.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='friends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='startedchat',
            field=models.JSONField(null=True),
        ),
    ]
